getMinMax
js-tasks-ru/jsbasic-20220519_vyacheslav-shitikov pull request #6
Opened 2022-06-03 09:24 UTC by shitikov14

2022-06-03 09:26 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-06-03 12:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-06-03 15:30 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-05 12:53 UTC, SinimaWath requested changes

2022-06-05 12:53 UTC, SinimaWath commented on 4-module/2-task/index.js
> +  let getTable = document.body.firstElementChild;
Надо использовать table, который передали в аргументе - `table`

2022-06-05 19:49 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-06-06 15:15 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-06-07 11:52 UTC, SinimaWath commented
не нужно удалять задачи, если уже их добавили :)

2022-06-07 13:05 UTC, shitikov14 commented
А когда засчитаются мои выполненные задачи?

2022-06-08 11:02 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-06-08 11:51 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-06-10 13:27 UTC, SinimaWath commented
Задачи засчитаются когда я их замержу. Все ок, в текущих задачах.

Но чтобы принять ПР, надо чтобы ты решил удаленную задачу 4-3

2022-06-10 15:42 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2022-06-13 09:27 UTC, SinimaWath approved these changes

2022-06-13 09:28 UTC, merged